name: envpy3
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - opencv3
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - imageio=2.1.2
    - pip:
        - tensorflow==0.12.1
        - keras==1.2.1
